services:
  robot:
    image: eurobot_2025:latest
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - CMAKE_PREFIX_PATH=/opt/ros/humble
    volumes:
      - ./src:/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ./run.sh

  camera:
    image: eurobot_2025_camera:latest
    build:
      context: ./camera/
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - QT_DEBUG_PLUGINS=0
      - CMAKE_PREFIX_PATH=/opt/ros/humble
    volumes:
      - ./camera/src:/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/video0:/dev/video0

    command: ./run.sh