obstacle_extractor_node:
  ros__parameters:
    active: true
    use_scan: true 
    use_pcl: false 
    use_sim_time: false
    use_split_and_merge: true 
    circles_from_visibles: true 
    discard_converted_segments: true 
    transform_coordinates: true 
    min_group_points: 3
    max_group_distance: 0.1
    distance_proportion: 0.00628
    max_split_distance: 0.5 
    max_merge_separation: 0.1 
    max_merge_spread: 0.2 
    max_circle_radius: 0.1
    radius_enlargement: 0.0 
    frame_id: base_footprint