services:
  robot:
    image: eurobot_2025:latest
    build:
      context: $ROOT_DIR
      dockerfile: $ROOT_DIR/docker/Dockerfile
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - CMAKE_PREFIX_PATH=/opt/ros/humble
      - MAKE_MAP=$MAKE_MAP
    volumes:
      - $ROOT_DIR/src/ros2:/ros2_ws/src
      - $ROOT_DIR/data:/data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/video0:/dev/video0
    command: ./run.sh