strategy_node:
  ros__parameters:
    waypoints:
      - [-0.69, -0.55, -1.57, # Первая куча банок
         -0.72, -0.87, -1.57, # Место первой сборки
          -0.4, -0.22,   0.0, # Вторая куча банок
         -0.69, -0.55, -1.57, # Место второй сборки
         -1.06, 0.303,   0.0, # Место ожидания
         -1.22,  0.89,   0.0  # Место финиша
        ]  # x, y, theta ==> Каждые 3 числа - одна точка.
      # - [-1.22, 0.89, 0.0] # На место финиша
    elevator_order:
      - [3, 1, 2, 1, 2, 0] # Порядок команд элеватора
    time_until_end: 90
    obstacle_release: 
      - ["right_upper_material", "center_material_right"]