strategy_node:
  ros__parameters:
    waypoints:
      - [-0.4, -0.35,   1.57, # Вторая куча банок
         -0.69, -0.55, -1.57, # Место второй сборки 
        #  -0.75, -0.478, -1.57, # Первая куча банок
        #  -0.72, -0.87, -1.57, # Место первой сборки
         
         -0.9, 0.2, 1.57, # Место ожидания
         -1.15,  0.82, 1.57 # Место финиша
        ]  # x, y, theta ==> Каждые 3 числа - одна точка.
      # - [-1.22, 0.89, 0.0] # На место финиша
    elevator_order:
     # - [3, 1, 2, 1, 2, 0] # Порядок команд элеватора
     - [3, 1, 2, 0] # Порядок команд элеватора
    time_until_end: 90
    obstacle_release: 
      - ["upper_material_right", "center_material_right"]
    term_order: 
      # - [20,8,8,50]
      - [20, 8, 10]